version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "17:00"
      timezone: "America/Los_Angeles"
  # We now use Renovate instead of Dependabot for Cargo dependencies, because it handles
  # distinguishing breaking and non-breaking changes better.
  # - package-ecosystem: "cargo"
