//! [`GltfTextureAllocator`], produces glTF-compatible textures for blocks.

use std::collections::{BTreeMap, HashMap};
use std::io;
use std::iter;
use std::mem;
use std::sync::{Arc, Mutex, OnceLock};

use gltf_json::validation::Checked::Valid;

use all_is_cubes::block::Evoxel;
use all_is_cubes::euclid::{Point2D, Point3D, Scale, Vector2D, point2};
use all_is_cubes::math::{Axis, Cube, GridAab, GridRotation, Gridgid, Vol};
use all_is_cubes_mesh::texture::{self, TilePoint};

use crate::gltf::GltfDataDestination;
use crate::gltf::glue::Lef32;

// -------------------------------------------------------------------------------------------------

/// Coordinate system marker type for positions in the texture atlas generated by
/// [`GltfTextureAllocator`].
pub(crate) struct AtlasUv;

/// The mapping from [`GltfTextureAllocator`] allocations to texture atlas UV coordinates.
pub(crate) struct UvMap {
    /// Maps each [`PlaneId`] to its origin (upper-left corner as viewed in an image viewer)
    /// in the atlas, in texels.
    positioning: HashMap<PlaneId, Point2D<u32, texture::TexelUnit>>,

    /// Scale factor from texels ([`texture::TexelUnit`]) to 0-1 UV coordinates as used by glTF.
    /// Stored as f64 to maximize precision up to the final result (TODO: is this necessary?)
    scale: Scale<f64, texture::TexelUnit, AtlasUv>,

    /// Texture coordinates of the center of a texel that is always opaque white.
    ///
    /// This special texel is used to allow mixing vertex colors with textures in the same mesh,
    /// by making one white while the other is meaningful.
    white: [Lef32; 2],
}

impl UvMap {
    /// Vertex tests need a `UvMap` to check the math with,
    /// but `UvMap`'s details otherwise belong to the texture allocator and atlas builder,
    /// so this function is for that special case only.
    #[cfg(test)]
    pub(in crate::gltf) fn new_for_testing(
        plane_id: PlaneId,
        offset: Point2D<u32, texture::TexelUnit>,
        white: Point2D<f32, AtlasUv>,
    ) -> Self {
        Self {
            positioning: HashMap::from([(plane_id, offset)]),
            // normally this would be less than 1 to create 0-1 coordinates,
            // but doing this instead keeps the test simple.
            scale: Scale::new(1.0),
            white: white.to_array().map(Lef32::new),
        }
    }

    /// Convert a point in a plane allocation to a UV point in the atlas texture.
    ///
    /// Panics if `plane_id` is not in the map.
    pub fn plane_to_atlas(
        &self,
        plane_id: PlaneId,
        texel_in_plane: Point2D<f32, texture::TexelUnit>, // TODO: more specific unit
    ) -> Point2D<f32, AtlasUv> {
        let origin_of_plane_in_atlas = self.positioning[&plane_id];
        self.scale
            .transform_point(
                origin_of_plane_in_atlas.map(f64::from) + texel_in_plane.map(f64::from).to_vector(),
            )
            .cast::<f32>()
    }

    /// Returns the center of a texel that is opaque white.
    pub fn white(&self) -> [Lef32; 2] {
        self.white
    }
}

// -------------------------------------------------------------------------------------------------

/// [`texture::Allocator`] implementation for glTF exports.
///
/// You may use this with [`SpaceMesh`] to create textured meshes that can be exported.
///
/// This allocator does not perform deallocation, on the assumption that as the glTF asset
/// is constructed, the meshes going into it are created and dropped rather than kept to
/// the end.
///
/// [`SpaceMesh`]: all_is_cubes_mesh::SpaceMesh
#[derive(Clone, Debug)]
pub struct GltfTextureAllocator {
    destination: GltfDataDestination,
    gatherer: Gatherer,
}

impl GltfTextureAllocator {
    /// Public access is via [`GltfWriter::texture_allocator()`].
    pub(crate) fn new(destination: GltfDataDestination) -> Self {
        Self {
            destination,
            gatherer: Gatherer::default(),
        }
    }

    pub(crate) fn is_empty(&self) -> bool {
        self.gatherer.is_empty()
    }

    pub(crate) fn write_png_atlas(&self) -> Result<Atlas<gltf_json::Buffer>, io::Error> {
        let Atlas {
            reflectance,
            emission,
            uv_map,
        } = self.gatherer.build_atlas();

        // Store image data to glTF buffers
        // TODO: add error context
        let reflectance = self.write_one_image(&reflectance)?;
        let emission = if let Some(emission) = emission {
            Some(self.write_one_image(&emission)?)
        } else {
            None
        };

        Ok(Atlas {
            reflectance,
            emission,
            uv_map,
        })
    }

    fn write_one_image(
        &self,
        image: &image::ImageBuffer<image::Rgba<u8>, Vec<u8>>,
    ) -> Result<gltf_json::Buffer, io::Error> {
        self.destination.write(String::from("texture"), "texture", "png", |w| {
            // `image` wants `Write + Seek` but `w` is not currently `Seek`
            let mut tmp = io::Cursor::new(Vec::new());
            image
                .write_to(&mut tmp, image::ImageFormat::Png)
                .expect("failed to write image to in-memory buffer");
            w.write_all(tmp.into_inner().as_slice())?;
            Ok(())
        })
    }
}

impl texture::Allocator for GltfTextureAllocator {
    type Tile = GltfTile;
    type Point = GltfAtlasPoint;

    fn allocate(&self, bounds: GridAab, channels: texture::Channels) -> Option<GltfTile> {
        assert!(!bounds.is_empty());

        Some(GltfTile {
            bounds,
            reflectance: TexelsCell::default(),
            emission: match channels {
                texture::Channels::Reflectance => None,
                texture::Channels::ReflectanceEmission => Some(TexelsCell::default()),
            },
            gatherer: self.gatherer.clone(),
        })
    }
}

/// [`texture::Tile`] produced by [`GltfTextureAllocator`].
///
/// You should not generally need to refer to this type.
//---
// Implementation notes: Since glTF does not support 3D textures, we must slice the provided
// texels into 2D sections. Therefore, this is just a container for the texels, not a handle
// to the actual atlas.
#[derive(Clone, Debug, PartialEq)]
pub struct GltfTile {
    bounds: GridAab,

    /// When we are sliced, we report the slice to the gatherer so that it can be placed in the
    /// texture atlas.
    gatherer: Gatherer,

    // Actual texel storage
    reflectance: TexelsCell,
    emission: Option<TexelsCell>,
}

impl GltfTile {
    fn allocate_texels(&self) -> Vec<[u8; 4]> {
        vec![[0, 0, 0, 0]; self.bounds.volume().unwrap()]
    }
}

impl texture::Tile for GltfTile {
    type Point = GltfAtlasPoint;
    type Plane = GltfTexturePlane;
    const REUSABLE: bool = false;
    const SUPPORTS_3D: bool = false;

    fn write(&mut self, data: Vol<&[Evoxel]>) {
        assert_eq!(data.bounds(), self.bounds());

        let mut reflectance_buffer = self.allocate_texels();
        let mut emission_buffer = self.emission.is_some().then(|| self.allocate_texels());
        texture::copy_voxels_into_xmaj_texture(
            data,
            &mut reflectance_buffer,
            emission_buffer.as_deref_mut(),
        );

        // OK to panic on failure because if we do, the caller ignored Self::REUSABLE.
        self.reflectance
            .set(reflectance_buffer)
            .expect("cannot overwrite glTF textures");
        if let Some(emission_buffer) = emission_buffer {
            self.emission
                .as_mut()
                .unwrap()
                .set(emission_buffer)
                .expect("cannot overwrite glTF textures");
        }
    }

    fn bounds(&self) -> GridAab {
        self.bounds
    }

    fn channels(&self) -> texture::Channels {
        match self.emission {
            Some(_) => texture::Channels::ReflectanceEmission,
            None => texture::Channels::Reflectance,
        }
    }

    #[track_caller]
    fn slice(&self, sliced_bounds: GridAab) -> Self::Plane {
        let axis = texture::validate_slice(self.bounds, sliced_bounds);

        let rotation = match axis {
            // TODO: decide which exact rotations to use
            Axis::X => GridRotation::RZYx, // X is flat, so rotate about Y
            Axis::Y => GridRotation::RXZy, // Y is flat, so rotate about X
            Axis::Z => GridRotation::IDENTITY,
        };

        let plane_id = self.gatherer.insert(AtlasEntry {
            reflectance_texels: self.reflectance.clone(),
            emission_texels: self.emission.clone(),
            source_bounds: self.bounds,
            sliced_bounds,
            rotation,
        });

        GltfTexturePlane {
            plane_id,
            bounds: sliced_bounds,
            rotation,
        }
    }

    fn grid_to_texcoord_3d(&self, _: TilePoint) -> Self::Point {
        unimplemented!(
            "GltfTextureAllocator::SUPPORTS_3D is false; this function should not have been called"
        )
    }
}

/// [`texture::Plane`] produced by [`GltfTextureAllocator`].
///
/// You should not generally need to refer to this type.
#[derive(Clone, Debug, PartialEq)]
pub struct GltfTexturePlane {
    plane_id: PlaneId,
    bounds: GridAab,
    rotation: GridRotation,
}

/// Identifier of a particular [`texture::Plane`] allocated by [`GltfTextureAllocator`] and
/// packed into a 2D texture coordinate space.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub(crate) struct PlaneId(pub(in crate::gltf) u64);

impl texture::Plane for GltfTexturePlane {
    type Point = GltfAtlasPoint;

    fn grid_to_texcoord(&self, tc_in_tile: TilePoint) -> Self::Point {
        // TODO: precompute more of this
        let rot_tc: TilePoint = self
            .rotation
            .to_rotation_matrix()
            .to_free()
            .with_source::<texture::TexelUnit>() // TODO: avoid these unit changes by being able to get Transform3D straight from GridRotation
            .with_destination::<texture::TexelUnit>()
            .transform_point3d(tc_in_tile.map(f64::from))
            .unwrap()
            .map(|c| c as f32);
        let rot_bounds = self.bounds.transform(self.rotation.into()).unwrap();

        // Translate to get coordinates within the rotated-to-XY plane.
        let point_within = rot_tc - rot_bounds.lower_bounds().to_f32().cast_unit();
        debug_assert!(
            point_within.z >= 0.0 && point_within.z <= 1.0,
            "rotation did not properly flatten to zero Z: {tc_in_tile:?} -> {point_within:?}"
        );
        let point_within = point_within.to_2d().to_point();

        GltfAtlasPoint {
            plane_id: self.plane_id,
            point_within,
        }
    }
}

/// Point type produced by [`GltfTextureAllocator`].
///
/// You should not generally need to refer to this type.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct GltfAtlasPoint {
    /// Unique ID of the plane (texture atlas tile).
    pub(crate) plane_id: PlaneId,
    /// Point within the plane, still with 1 unit = 1 texel coordinates.
    pub(crate) point_within: Point2D<f32, texture::TexelUnit>,
}

// -------------------------------------------------------------------------------------------------

/// Generates the atlas textures and necessary glTF entities.
pub(super) fn insert_block_texture_atlas(
    root: &mut gltf_json::Root,
    allocator: &GltfTextureAllocator,
    min_filter: gltf_json::texture::MinFilter,
) -> Result<Atlas<gltf_json::Index<gltf_json::Texture>>, io::Error> {
    let Atlas {
        reflectance,
        emission,
        uv_map,
    } = allocator.write_png_atlas()?;

    let sampler = root.push(gltf_json::texture::Sampler {
        mag_filter: Some(Valid(gltf_json::texture::MagFilter::Nearest)),
        min_filter: Some(Valid(min_filter)),
        name: Some("block texture".into()),
        wrap_s: Valid(gltf_json::texture::WrappingMode::ClampToEdge),
        wrap_t: Valid(gltf_json::texture::WrappingMode::ClampToEdge),
        extensions: None,
        extras: Default::default(),
    });
    let reflectance = insert_one_image(root, "reflectance", reflectance, sampler);
    let emission = emission.map(|emission| insert_one_image(root, "emission", emission, sampler));

    Ok(Atlas {
        reflectance,
        emission,
        uv_map,
    })
}

/// Starting with a `Buffer` of texture data, inserts all the entities for a `Texture`.
fn insert_one_image(
    root: &mut gltf_json::Root,
    name: &'static str,
    image_buffer: gltf_json::Buffer,
    sampler: gltf_json::Index<gltf_json::texture::Sampler>,
) -> gltf_json::Index<gltf_json::Texture> {
    let block_texture_len = image_buffer.byte_length;
    let block_texture_buffer = root.push(image_buffer);
    let block_texture_buffer_view = root.push(gltf_json::buffer::View {
        buffer: block_texture_buffer,
        byte_length: block_texture_len,
        byte_offset: None,
        byte_stride: None,
        name: Some(name.into()),
        target: None,
        extensions: None,
        extras: Default::default(),
    });
    let block_texture_image = root.push(gltf_json::Image {
        buffer_view: Some(block_texture_buffer_view),
        mime_type: Some(gltf_json::image::MimeType("image/png".into())),
        name: Some(name.into()),
        uri: None,
        extensions: None,
        extras: Default::default(),
    });

    root.push(gltf_json::Texture {
        name: None,
        sampler: Some(sampler),
        source: block_texture_image,
        extensions: None,
        extras: Default::default(),
    })
}

// -------------------------------------------------------------------------------------------------

/// Interior-mutable accumulator of textures to put in the atlas.
#[derive(Clone, Debug, Default)]
pub(super) struct Gatherer(Arc<Mutex<Vec<AtlasEntry>>>);

impl Gatherer {
    pub(crate) fn is_empty(&self) -> bool {
        self.0.lock().expect("mutex in atlas gatherer").is_empty()
    }

    /// Inserts a new atlas entry corresponding to a plane and returns its ID.
    pub fn insert(&self, entry: AtlasEntry) -> PlaneId {
        let mut data = self.0.lock().expect("mutex in atlas gatherer");
        let plane_id = PlaneId(u64::try_from(data.len()).unwrap());
        data.push(entry);
        plane_id
    }

    /// Take all currently allocated textures and produce a texture atlas, and the UV map which
    /// specifies where in the atlas each [`GltfTexturePlane`] may be found.
    ///
    /// After this method is called, the allocator is no longer in a usable state
    /// because the data has been removed.
    pub(crate) fn build_atlas(&self) -> Atlas<image::RgbaImage> {
        let entries: Vec<AtlasEntry> =
            mem::take(&mut self.0.lock().expect("mutex in atlas gatherer"));

        build_atlas_impl(entries)
    }
}

impl PartialEq for Gatherer {
    fn eq(&self, other: &Self) -> bool {
        Arc::ptr_eq(&self.0, &other.0)
    }
}

/// Details of one piece of texture that must be included in the generated texture atlas.
#[derive(Debug)]
pub(super) struct AtlasEntry {
    pub(super) reflectance_texels: TexelsCell,
    pub(super) emission_texels: Option<TexelsCell>,
    /// Bounds of the 3D region containing `*_texels`.
    pub(super) source_bounds: GridAab,
    /// Bounds of the 2D region sliced out of `source_bounds`.
    /// Must have at least one axis of size 1.
    pub(super) sliced_bounds: GridAab,
    /// Rotation that will rotate `sliced_bounds` to be flat in the atlas.
    pub(super) rotation: GridRotation,
}

impl AtlasEntry {
    pub fn rotated_slice_bounds(&self) -> GridAab {
        self.sliced_bounds.transform(self.rotation.into()).unwrap() // cannot overflow because block sizes are limited 
    }
}

/// Storage shared by [`GltfTile`]s for writing and [`Gatherer::build_atlas()`] for reading.
type TexelsCell = Arc<OnceLock<Vec<[u8; 4]>>>;

/// Data structure for a built texture atlas, and its image data, or a reference to its image data,
/// in some form `I`.
pub(crate) struct Atlas<I> {
    pub reflectance: I,
    pub emission: Option<I>,
    pub uv_map: UvMap,
}

// -------------------------------------------------------------------------------------------------

/// Arranges and generates the texture atlas, given all the allocated tiles and planes.
///
/// Returns:
/// * reflectance image
/// * emission image (if it is to have any content)
/// * UV map for updating texture coordinates
///
/// Use this function via [`Gatherer::build_atlas()`].
#[allow(clippy::needless_pass_by_value, reason = "semantically, is consumed")]
fn build_atlas_impl(entries: Vec<AtlasEntry>) -> Atlas<image::RgbaImage> {
    use rectangle_pack as rp;

    /// Identifier of one of the things we will ask `rectangle_pack` to place.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Ord, PartialOrd)]
    enum RectId {
        /// Special 1×1 rectangle containing white only.
        White,
        /// A [`GltfTexturePlane`].
        Texture(PlaneId),
    }

    // Number of pixels to add to tiles to avoid bleeding (sampling texels outside the bounds
    // of a tile).
    let anti_bleed_padding: u32 = 2;

    // Step 1: compute `rects_to_place` which is the input to the `rectangle_pack` library.

    // TODO: add anti-bleed borders to atlas
    let mut rects_to_place: rp::GroupedRectsToPlace<RectId, ()> = rp::GroupedRectsToPlace::new();
    let mut has_emission = false;
    rects_to_place.push_rect(RectId::White, None, rp::RectToInsert::new(1, 1, 1));
    for (
        i,
        &AtlasEntry {
            reflectance_texels: _,
            ref emission_texels,
            source_bounds: _,
            sliced_bounds,
            rotation,
        },
    ) in iter::zip(0.., entries.iter())
    {
        let size = sliced_bounds
                    .transform(rotation.into())
                    .unwrap(/* cannot overflow? */)
                    .size();
        assert_eq!(
            size.depth, 1,
            "failed to rotate slice {sliced_bounds:?} into the XY plane \
                    with {rotation:?}: {size:?}"
        );
        rects_to_place.push_rect(
            RectId::Texture(PlaneId(i)),
            None,
            rp::RectToInsert::new(
                size.width + anti_bleed_padding * 2,
                size.height + anti_bleed_padding * 2,
                size.depth,
            ),
        );
        if emission_texels.is_some() {
            has_emission = true;
        }
    }

    // Step 2: attempt rectangle packing, with increasing texture sizes until one succeeds.

    let mut texture_size = 8;
    let placements: rp::RectanglePackOk<RectId, ()> = loop {
        // "Bins" correspond to multiple textures. We will use one bin,
        // because our goal is to fit everything into one texture rather than
        // requiring multiple meshes.
        let mut bins = BTreeMap::from([((), rp::TargetBin::new(texture_size, texture_size, 1))]);

        match rp::pack_rects(
            &rects_to_place,
            &mut bins,
            &rp::volume_heuristic,
            &rp::contains_smallest_box,
        ) {
            Ok(placements) => {
                break placements;
            }
            Err(rp::RectanglePackError::NotEnoughBinSpace) => {
                // Approximately double the area by scaling the side length by 7/5,
                // approximately sqrt(2).
                let new_texture_size = texture_size.wrapping_mul(7).wrapping_div(5);
                if new_texture_size > texture_size {
                    texture_size = new_texture_size;
                } else {
                    // We don’t expect to ever hit this but it guards against looping infinitely
                    panic!("numeric overflow while attempting to find fitting texture size");
                }
            }
        }
    };
    let scale = Scale::new(f64::from(texture_size).recip());

    // Step 3: build the atlas image using the chosen `placements`.

    let new_image = || image::RgbaImage::new(texture_size, texture_size);
    let mut reflectance_image = new_image();
    let mut emission_image = has_emission.then(new_image);
    let mut uv_of_white: Option<[Lef32; 2]> = None;
    for (&rect_id, &((), location_in_atlas)) in placements.packed_locations() {
        match rect_id {
            RectId::White => {
                // Draw the white texel into the texture.
                reflectance_image.put_pixel(
                    location_in_atlas.x(),
                    location_in_atlas.y(),
                    image::Rgba([255; 4]),
                );
                if let Some(ref mut emission_image) = emission_image {
                    emission_image.put_pixel(
                        location_in_atlas.x(),
                        location_in_atlas.y(),
                        image::Rgba([0; 4]),
                    );
                }

                // Compute the single UV value at the middle of the white texel
                uv_of_white = Some(
                    scale
                        .transform_point(
                            point2(location_in_atlas.x(), location_in_atlas.y()).map(f64::from)
                                + Vector2D::splat(0.5),
                        )
                        .to_f32()
                        .to_array()
                        .map(Lef32::new),
                );
            }
            RectId::Texture(plane_id) => {
                let entry = &entries[plane_id.0 as usize];

                copy_texels_to_atlas_images(
                    entry,
                    &entry.reflectance_texels,
                    anti_bleed_padding,
                    &mut reflectance_image,
                    location_in_atlas,
                );
                if let Some(ref emission_texels) = entry.emission_texels {
                    copy_texels_to_atlas_images(
                        entry,
                        emission_texels,
                        anti_bleed_padding,
                        emission_image.as_mut().expect("emission image"),
                        location_in_atlas,
                    );
                }
            }
        }
    }

    // Step 4: Save the placements in a `UvMap` for use by the texture coordinate rewriting step.

    let uv_map = UvMap {
        positioning: placements
            .packed_locations()
            .iter()
            .filter_map(|(&rect_id, &((), slice_location_in_atlas))| {
                if let RectId::Texture(plane_id) = rect_id {
                    Some((
                        plane_id,
                        point2(
                            slice_location_in_atlas.x() + anti_bleed_padding,
                            slice_location_in_atlas.y() + anti_bleed_padding,
                        ),
                    ))
                } else {
                    None
                }
            })
            .collect(),
        scale,
        white: uv_of_white.unwrap(),
    };

    Atlas {
        reflectance: reflectance_image,
        emission: emission_image,
        uv_map,
    }
}

fn copy_texels_to_atlas_images(
    entry: &AtlasEntry, // used only for its dimensions
    texels_cell: &TexelsCell,
    anti_bleed_padding: u32,
    atlas_image: &mut image::ImageBuffer<image::Rgba<u8>, Vec<u8>>,
    location_in_atlas: rectangle_pack::PackedLocation,
) {
    // By "rotated" we mean atlas coordinates and "unrotated" we mean original
    // `GltfTile` coordinates.
    let rotated_slice_bounds = entry.rotated_slice_bounds();
    let unrotate = Gridgid::from(entry.rotation.inverse());
    let texels_size = entry.source_bounds.size();
    let texels = texels_cell.get().expect("image texels not set -- TODO propagate error");

    // Copy slice from 3D `texels` into 2D atlas image.
    //
    // (x_in_rect, y_in_rect) are in terms of the padded rectangle and thus are larger
    // than the `GltfAtlasPlane`.
    for y_in_rect in 0..location_in_atlas.height() {
        for x_in_rect in 0..location_in_atlas.width() {
            // Remove padding to get positions within the `GltfAtlasPlane`
            // (but not yet unrotated).
            // cast_signed(): given that packing succeeded, these will be in bounds
            let pixel_position = Point3D::new(
                x_in_rect.cast_signed() - anti_bleed_padding.cast_signed(),
                y_in_rect.cast_signed() - anti_bleed_padding.cast_signed(),
                0,
            );

            // Position in the rotated-to-flat slice's coordinates, which are
            // relative to the allocated `GltfTile`.
            let position_in_rotated_slice =
                Cube::from(pixel_position + rotated_slice_bounds.lower_bounds().to_vector());
            let cube_in_rotated_slice = position_in_rotated_slice;

            // Position in the original requested slice's coordinates.
            let unrotated = unrotate.transform_cube(cube_in_rotated_slice);

            // Clamp the position to the tile bounds; this causes the `tile_padding` to
            // be filled with copies instead of being out of bounds.
            let clamped_unrotated = entry.sliced_bounds.clamp_cube(unrotated).unwrap();

            // Position relative to 3D tile bounds.
            let position_in_texels =
                (clamped_unrotated.lower_bounds() - entry.source_bounds.lower_bounds()).to_u32();
            // Index into the `texels` array at that position.
            let index_in_texels = position_in_texels.x
                + texels_size.width
                    * (position_in_texels.y + texels_size.height * position_in_texels.z);

            let texel = texels[usize::try_from(index_in_texels).unwrap()];
            atlas_image.put_pixel(
                location_in_atlas.x() + x_in_rect,
                location_in_atlas.y() + y_in_rect,
                image::Rgba(texel),
            );
        }
    }
}

// -------------------------------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use all_is_cubes::block;
    use all_is_cubes::math::Rgba;
    use all_is_cubes_mesh::texture::{Allocator, Channels, Tile};
    use std::fs;

    /// TODO: this is just a smoke-test; add more rigorous tests.
    #[test]
    fn allocator_creates_file() {
        let temp_dir = tempfile::tempdir().unwrap();
        let mut file_base_path = temp_dir.path().to_owned();
        file_base_path.push("filetest.gltf");

        let allocator =
            GltfTextureAllocator::new(GltfDataDestination::new(Some(file_base_path), 0));
        let mut tile = allocator
            .allocate(GridAab::ORIGIN_CUBE, Channels::Reflectance)
            .expect("allocation");
        tile.write(
            block::Evoxels::from_one(Evoxel::from_color(Rgba::from_srgb8([1, 2, 3, 4])))
                .as_vol_ref(),
        );
        drop(tile);

        allocator.write_png_atlas().unwrap();

        assert_eq!(
            fs::read_dir(temp_dir.path())
                .unwrap()
                .map(|e| e.unwrap().file_name().into_string().unwrap())
                .collect::<Vec<String>>(),
            vec!["filetest-texture.png"],
        );
    }
}
